substitutions:
  name: "sensor-pkg-b-c4001"
  friendly_name: "Indoor Multi-Sensor Pkg B Radar C4001"

  # Settings
  use_pir_in_presence: "true"
  # Status LED Configuration
  status_day_brightness: "0.5"
  status_night_brightness: "0.20"
  status_daytime_lux: "12.0"
  status_nighttime_lux: "7.0"
  # CO Configuration
  co_temp_id: "temperature"
  co_offset: "0.0"
  co_sensitivity: "2.000e-9"
  co_manufacture_date: "Unknown"
  co_serial_number: "111111111111111111"
  # Temperature Configuration
  temperature_offset: "0.0"
  # Humidity Configuration
  humidity_offset: "0.0"
  # CO₂ Configuration
  co2_calibration_date: "Unknown"
  # Automatically controlled Vent
  vent_ha_entity: fan.vent_id
  vent_use_humidity: "true"
  vent_use_co2: "true"
  vent_min_on_time: "15"
  vent_hum_on_trigger: "10.0"
  vent_hum_off_trigger: "2.5"
  vent_co2_on_trigger: "1100"
  vent_co2_off_trigger: "900"

packages:
  remote_package_files:
    url: https://github.com/mikelawrence/esphome-indoor-multi-sensor
    refresh: 1h
    files:
      # Main Config Files
      - config/common/pkgb-sht4x.yaml
      - config/common/pkgb-scd4x.yaml
      - config/common/pkgb-sgp4x.yaml
      - config/common/radar-c4001.yaml

      # ADDITIONAL SENSORS
      # Carbon Dioxide (CO) - Figaro TGS5141 sensor
      - config/common/add-co.yaml
      # Energy Usage - INA2XX sensor to measure Voltage, Power and Energy Usage
      - config/common/add-ina2xx.yaml
      # Light Level - TSL2591 sensor
      - config/common/add-tsl2591.yaml
      # Barometric Pressure - BMP581 sensor
      - config/common/add-bmp581.yaml
      # Microphone - Adds Sound Level meter
      - config/common/add-microphone.yaml

      # FEATURES
      # SEN6X Pressure Compensation - Adds pressure compensation to SEN6X
      - config/common/feat-scd4x-press-comp.yaml
      # Automatic Vent - Use humidity and CO₂ control a bathroom vent
      # - config/common/feat-auto-vent.yaml

# Add custom components
external_components:
  - source: github://mikelawrence/esphome-components
    components: [dfrobot_c4001, bmp581]

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  on_boot:
    - priority: -100
      then:
        - script.execute: update_status_led
  on_shutdown:
    - priority: 700
      then:
        - light.turn_off:
            id: led_status

# ESP32-S3-WROOM-2-N32R16V
esp32:
  board: esp32s3box
  variant: ESP32S3
  flash_size: 32MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# This PSRAM can actually support faster than 80MHz
psram:
  mode: octal
  speed: 80MHz

# To be able to get logs from the device via serial and api.
logger:
  id: logger_common
  level: DEBUG

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome

# WiFI AP, required when allowing user to provision WiFi credentials
wifi:
  ap:

# Fallback when WiFi configuration fails
# required when allowing user to provision WiFi credentials using WiFi
captive_portal:

# Allows user to provision WiFi credentials with Bluetooth using Improv standard
esp32_improv:
  authorizer: none

# Allow user to provision WiFi credentials with USB port using Improv standard
improv_serial:

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

debug:
  update_interval: 60s

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

i2c:
  - id: i2c1_bus
    sda: GPIO48
    scl: GPIO47
    frequency: 400kHz
    scan: true

i2s_audio:
  - id: speaker_i2s
    i2s_lrclk_pin: GPIO12
    i2s_bclk_pin: GPIO11

script:
  - id: update_status_led
    mode: restart
    then:
      lambda: |-
        static bool last_state;
        static float last_r, last_g, last_b, last_brightness = ${status_night_brightness};
        bool state;
        float r, g, b, brightness = last_brightness;
        if(last_brightness == ${status_day_brightness}) {
          // daytime
          if(id(lux).state < ${status_nighttime_lux}) {
            brightness = ${status_night_brightness};
            ESP_LOGD("status", "Status LED switched to nighttime brightness");
          }
        } else {
          // nighttime
          if(id(lux).state > ${status_daytime_lux}) {
            brightness = ${status_day_brightness};
            ESP_LOGD("status", "Status LED switched to daytime brightness");
          }
        }
        if(!id(led_enable).state) {
          state = false;
        } else {
          if (id(presence).state) {
            state = true;
            r = 0.0; g = 0.0; b = 1.0;
          } else {
            state = false;
          }
        }
        if (state == false) {
          if (last_state == true) {
            id(led_status).turn_off().set_transition_length(0).perform();
            ESP_LOGD("status", "Status LED turned off");
          }
        } else {
          if ((last_state == false) || (last_r != r) || (last_g != g) ||
              (last_b != b) || (last_brightness != brightness)) {
            id(led_status).turn_on().set_transition_length(0).
              set_rgb(r, g, b).set_brightness(brightness).perform();
            ESP_LOGD("status", "Status LED turned on");
          }
        }
        last_state = state;
        last_brightness = brightness;
        last_r = r;
        last_g = g;
        last_b = b;

power_supply:
  # Enable DAC Power
  - id: dac_enable
    pin: GPIO9
    enable_on_boot: true

binary_sensor:
  - platform: template
    name: Presence
    id: presence
    device_class: presence
    lambda: |-
      if(id(presence_mmwwave).state or
        (id(pir_enable).state && id(motion_pir).state)) {
        return true;
      } else {
        return false;
      }
    on_state:
      then:
        script.execute: update_status_led
  - platform: gpio
    id: motion_pir
    name: PIR Motion
    device_class: motion
    pin:
      number: GPIO38
    filters:
      - delayed_off: !lambda "return id(internal_timeout).state;"

button:
  - platform: restart
    name: "Restart"
    entity_category: CONFIG

light:
  - platform: esp32_rmt_led_strip
    id: led_status
    rgb_order: RGB
    pin: GPIO8
    num_leds: 1
    chipset: ws2812

media_player:
  - platform: speaker
    name: "Speaker Media Player"
    id: speaker_media_player_id
    media_pipeline:
      speaker: media_spk_resampling_input
      num_channels: 2
    announcement_pipeline:
      speaker: announcement_spk_resampling_input
      num_channels: 1
    files:
      - id: co_alarm_sound
        file: https://github.com/mikelawrence/esphome-indoor-multi-sensor/raw/refs/heads/main/config/media/CO-alarm-message.mp3

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

speaker:
  - platform: i2s_audio
    id: speaker_id
    i2s_audio_id: speaker_i2s
    dac_type: external
    i2s_dout_pin: GPIO10
    sample_rate: 48000
  - platform: mixer
    id: mixer_speaker_id
    output_speaker: speaker_id
    source_speakers:
      - id: announcement_spk_mixer_input
      - id: media_spk_mixer_input
  - platform: resampler
    id: media_spk_resampling_input
    output_speaker: media_spk_mixer_input
    sample_rate: 48000
  - platform: resampler
    id: announcement_spk_resampling_input
    output_speaker: announcement_spk_mixer_input
    sample_rate: 48000

switch:
  - platform: template
    name: PIR Enable
    id: pir_enable
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
  - platform: template
    name: LED Enable
    id: led_enable
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      script.execute: update_status_led
    on_turn_off:
      script.execute: update_status_led
