substitutions:
  name: "sensor-pkg-a-ld2410"
  friendly_name: "Indoor Multi-Sensor Pkg A Radar LD2410"

  # Settings
  use_pir_in_presence: "true"
  # Status LED Configuration
  status_day_brightness: "0.5"
  status_night_brightness: "0.20"
  status_daytime_lux: "12.0"
  status_nighttime_lux: "7.0"
  # CO Configuration
  co_temp_id: "temperature"
  co_offset: "0.0"
  co_sensitivity: "2.000e-9"
  co_manufacture_date: "Not Set"
  co_serial_number: "111111111111111111"
  # Temperature Configuration
  temperature_offset: "0.0"
  # Humidity Configuration
  humidity_offset: "0.0"
  # CO₂ Configuration
  co2_calibration_date: "Not Set"
  # Automatically controlled Vent
  vent_ha_entity: fan.vent_id
  vent_use_humidity: "true"
  vent_use_co2: "true"
  vent_min_on_time: "15"
  vent_hum_on_trigger: "10.0"
  vent_hum_off_trigger: "2.5"
  vent_co2_on_trigger: "1100"
  vent_co2_off_trigger: "900"

packages:
  remote_package_files:
    url: https://github.com/mikelawrence/esphome-indoor-multi-sensor
    # ref: dev
    refresh: 1h
    files:
      # Main Config Files
      - config/common/pkga-sen6x.yaml
      - config/common/radar-ld2410.yaml

      # ADDITIONAL SENSORS
      # Carbon Dioxide (CO) - Figaro TGS5141 sensor
      - config/common/add-co.yaml
      # Energy Usage - INA2XX sensor to measure Voltage, Power and Energy Usage
      - config/common/add-ina2xx.yaml
      # Light Level - TSL2591 sensor
      - config/common/add-tsl2591.yaml
      # Barometric Pressure - BMP581 sensor
      - config/common/add-bmp581.yaml
      # Microphone - Adds Sound Level meter
      - config/common/add-microphone.yaml

      # FEATURES
      # SEN6X Pressure Compensation - Adds pressure compensation to SEN6X
      - config/common/feat-sen6x-press-comp.yaml
      # Automatic Vent - Use humidity and CO₂ control a bathroom vent
      # - config/common/feat-auto-vent.yaml

# Add custom components
external_components:
  - source:
      type: git
      url: https://github.com/mikelawrence/esphome-components
      # ref: dev
    refresh: 1h
    components: [sen5x, bmp581, tsl2591]

# ESP32-S3-WROOM-2-N32R16V
esp32:
  board: esp32s3box
  variant: ESP32S3
  flash_size: 32MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

# This PSRAM can actually support faster than 80MHz
psram:
  mode: octal
  speed: 80MHz

# To be able to get logs from the device via serial and api.
logger:
  id: logger_common
  level: DEBUG

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome
    id: ota_esphome

# WiFI AP, required when allowing user to provision WiFi credentials
wifi:
  ap:

# Fallback when WiFi configuration fails
# required when allowing user to provision WiFi credentials using WiFi
captive_portal:

# Allows user to provision WiFi credentials with Bluetooth using Improv standard
esp32_improv:
  authorizer: none

# Allow user to provision WiFi credentials with USB port using Improv standard
improv_serial:

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

debug:
  update_interval: 60s

web_server:
  port: 80

